food_delivery/apps/core_app/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'core_app'
urlpatterns = [
     url (r'^$', views.HomeView.as_view(), name='home'),
     url (r'^sign-in/', views.logout_required(auth_views.login), 
        {"template_name":"core_app/sign_in.html"},
        name = "sign-in"),
     url (r'^sign-up/', views.logout_required(views.SignUpView.as_view()),
        name = "sign-up"),
     url (r'^logout/', auth_views.logout, 
        {"next_page":"/"},
        name = "logout"),
     url (r'^account/$', views.account, name="account"),
     url (r'^account/change-password/$', auth_views.password_change,
        {"post_change_redirect": "core_app:password_change_done","template_name":"core_app/change_password.html"}, name="change-password"),
     url (r'^account/change-password/done/$', auth_views.password_change_done,
        {"template_name":"core_app/password_change_done.html"}, name="password_change_done"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_delivery/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('core_app.urls',namespace = "core_app")),
    url(r'^cart/', include('cart.urls', namespace = "cart")),
]

food_delivery/apps/core_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.html import format_html


GLOBAL_NAME_LENGTH = 140
GLOBAL_ADDRESS_LENGTH = 500


class ComplexDinner(models.Model):
    dinner_name = models.CharField(max_length=GLOBAL_NAME_LENGTH, verbose_name="Название")
    cost = models.IntegerField(default = 0, verbose_name="Цена")
    description = models.TextField(verbose_name="Описание")
    dinner_img = models.ImageField(upload_to="dinners_images/", verbose_name="Изображение", blank=False)

    def __str__(self):
        return self.dinner_name

    class Meta:
        verbose_name = "Обед"
        verbose_name_plural = "Обеды"


class Meal(models.Model):
    MEAL_CATEGORY = (
        ("DRINKS", "Напитки"),
        ("SALADS", "Салаты"),
        ("SUSHI", "Суши/Роллы"),
        ("PIZZA", "Пицца"),
        ("SNACKS", "Закуски"),
        ("SOUPS", "Супы"),
        ("MAIN_DISHES", "Вторые блюда"),
        ("DESSERTS", "Десерты"),
    )
    dinner = models.ForeignKey(ComplexDinner, verbose_name="Входит в состав обеда", blank=True, null=True)
    meal_name = models.CharField(max_length=GLOBAL_NAME_LENGTH, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    cost = models.IntegerField(default=0, verbose_name="Цена")
    category = models.CharField(choices=MEAL_CATEGORY, max_length=20, verbose_name="Категория")
    meal_img = models.ImageField(upload_to="meals_images/", verbose_name="Изображение", blank=False)


    def __str__(self):
        return self.meal_name

    def meal_image_thumbnail(self):
        if self.meal_img:
            return format_html('<img src="{}" width="100" height="80" />'.format(self.meal_img.url))
        else:
            return "Изображение еще не добавлено"

    meal_image_thumbnail.allow_tags = True
    meal_image_thumbnail.short_description = 'Изображение'

    class Meta:
        verbose_name = "Блюдо"
        verbose_name_plural = "Блюда"


class Customer(models.Model): 
    user = models.OneToOneField(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    phone = models.CharField(max_length=GLOBAL_NAME_LENGTH, verbose_name="Телефон", blank=True, null=True)
    address = models.CharField(max_length=GLOBAL_ADDRESS_LENGTH, verbose_name="Адрес", blank=True, null=True)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = "Заказчик"
        verbose_name_plural = "Заказчики"


class Order(models.Model): 
    NEW_ORDER = 1
    WORKING = 2
    DONE = 3

    ORDER_STATUS = (
        (NEW_ORDER, 'Новый заказ'), (WORKING, 'В работе'), (DONE, 'завершен')
        )
    
    customer = models.ForeignKey(Customer, verbose_name="Заказчик")
    status = models.IntegerField(choices=ORDER_STATUS, verbose_name="Статус заказа")
    address = models.CharField(max_length=GLOBAL_ADDRESS_LENGTH, verbose_name="Адрес")
    created_at_time = models.DateTimeField(default = timezone.now, verbose_name="Время заказа")
    delivered_at_time = models.DateTimeField(blank = True, null = True, verbose_name="Время доставки")

    def __str__(self):
        return str(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    class Meta:
        ordering = ("-created_at_time",)
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"


class OrderDetails(models.Model): 
    order = models.ForeignKey(Order, verbose_name="Заказ")
    cost = models.IntegerField(null=True)
    quantity = models.IntegerField(verbose_name="Количество")

    def __str__(self):
        return str(self.id)

    def get_subtotal_cost(self):
        return self.quantity * self.cost

    class Meta:
        verbose_name = "Детали заказа"
        verbose_name_plural = "Детали заказа"

food_delivery/apps/core_app/forms.py
from django import forms
from django.contrib.auth.models import User
from core_app.models import Customer, Meal


GLOBAL_EMAIL_LENGTH = 100

class UserRegistrationForm(forms.ModelForm):
    email = forms.CharField(max_length=GLOBAL_EMAIL_LENGTH, required=True)
    password=forms.CharField(min_length = 8, label="Пароль", widget=forms.PasswordInput(), required=True)
    confirm_password=forms.CharField(label="Повторите пароль", widget=forms.PasswordInput(), required=True)

    def clean(self):
        cleaned_data = super(UserRegistrationForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.pop("confirm_password", None)

        if password != confirm_password:
            raise forms.ValidationError(
                "Пароли не совпадают!"
            )         
        return self.cleaned_data
    
    class Meta:
        model = User
        fields = ("username", "email", "password")

class UserUpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name")

class CustomerUpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ("phone", "address", )

food_delivery/apps/core_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.views.generic import TemplateView, FormView

from core_app.forms import UserRegistrationForm, UserUpdateProfileForm, CustomerUpdateProfileForm
from core_app.models import Customer
import food_delivery.settings as settings
import django.contrib.messages


def logout_required(view):
    def wrapper_func(request, *args, **kwargs):
        if not (request.user.is_authenticated):
            return view(request, *args, **kwargs)
        return redirect('core_app:home')
    return wrapper_func


@login_required(login_url = settings.LOGIN_URL)
@transaction.atomic
def account(request):
    if request.user.is_superuser or request.user.is_staff:
        return redirect (settings.ADMIN_STAFF_REDIRECT_URL)

    if request.method == "POST":
        user_profile_form = UserUpdateProfileForm(request.POST, instance=request.user)
        customer_profile_form = CustomerUpdateProfileForm(request.POST, instance=request.user.customer)
        if user_profile_form.is_valid() and customer_profile_form.is_valid():
            user_profile_form.save()
            customer_profile_form.save()
            return redirect("core_app:account")
        else:
            messages.error(request, _('Исправьте ошибки!'))
    else:
        user_profile_form = UserUpdateProfileForm(instance=request.user)
        customer_profile_form = CustomerUpdateProfileForm(instance=request.user.customer)
    return render(request, 'core_app/account.html', {
                "user_profile_form": user_profile_form,
                "customer_profile_form":customer_profile_form
                })


class HomeView(TemplateView):
    template_name = 'core_app/newed/base.html'


class SignUpView(FormView):

    template_name = 'core_app/sign_up.html'
    form_class = UserRegistrationForm
    success_url = settings.LOGIN_REDIRECT_URL

    def form_valid(self, form):
        new_user = User.objects.create_user(**form.cleaned_data)
        new_customer = Customer.objects.create(user=new_user)
        new_customer.save()

        login(self.request, authenticate(
            username = form.cleaned_data["username"],
            password = form.cleaned_data["password"]
         ))

        return redirect(self.get_success_url())


    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        return render(request, 'core_app/sign_up.html', {"form":form})

food_delivery/apps/core_app/templates/core_app/account.html
{% extends "core_app/base.html" %}
{% load bootstrap3 %}
{% block title %} Настройки личного кабинета {% endblock title %}

{%block header%} Здесь хэдер {%endblock header%}

{% block content%}
    <form method="post" class="change-userform">
        {% csrf_token %}
        {% bootstrap_form user_profile_form %}
        {% bootstrap_form customer_profile_form %}
        <button type="submit" class="btn btn-submit-red">Обновить данные</button>
        <a href="{% url 'core_app:change-password' %}">Сменить пароль</a>
    </form>
    
{% endblock content%}

food_delivery/apps/core_app/templates/core_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'core_app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core_app/css/custom_styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header> 
        {% block header %}  {% endblock header %} 
    </header>
    <main class="container-main">
        
        {% block content %}  {% endblock content %}
        
    </main>
    <script src="{% static 'core_app/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core_app/js/bootstrap.min.js' %}"></script>
</body>
</html>

food_delivery/apps/core_app/templates/core_app/change_password.html
{% extends "core_app/base.html" %}
{% load bootstrap3 %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-submit-red">Сменить пароль!</button>
  </form>
{% endblock content %}

food_delivery/apps/core_app/templates/core_app/home.html
{% extends "core_app/base.html" %}

{% block title%} Главная | {%endblock title%}

{% block header %}
  <div class="header-wrapper">
    <div class="header-content">
      {%  if user.is_authenticated %}
      <h1>Главная</h1> 
      <ul class="nav-panel">
        <li>Авторизованы как: {{ user.username }}</li>
           {% if user.is_superuser %}
          <li>
            <a href="{% url 'admin:index' %}">
                Перейти в админ-панель
            </a>
          </li>
            {% else %}
            <li>
                <a href="{% url 'core_app:account'%}">
                  Личный кабинет
                </a>
              </li>
            {% endif %}
        <li>
            <a href="{% url 'core_app:logout' %}">
              Выход
            </a>
        </li>
      </ul>    
      {% else %}
      <ul class="nav-panel">
        <li>
          <a href="{% url 'core_app:sign-up' %}">Регистрация</a>
        </li>
        <li>
          <a href="{% url 'core_app:sign-in' %}">Вход</a>
        </li>
      </ul>
    </div>
  </div>
      {% endif %}
{% endblock header %}

{% block content%}

{% endblock content%}

food_delivery/apps/core_app/templates/core_app/password_change_done.html
{% extends "core_app/base.html" %}

{% block content %}
<h1>Пароль успешно изменен!</h1>

<a href="{% url 'core_app:account' %}">Вернуться к настройкам аккаунта</a>
{% endblock content %}

food_delivery/apps/core_app/templates/core_app/sign_in.html
{% extends "core_app/signup_signin_base.html" %}
{% load bootstrap3 %}
{% block title%} Войти в систему {% endblock title%}

{% block header %} Вход в систему {%endblock header%}
{% block content%}
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-submit-red">Войти в систему</button>
  </form>
  <a href="{% url 'core_app:sign-up' %}">Или зарегистрироваться</a>
{% endblock content%}

food_delivery/apps/core_app/templates/core_app/sign_up.html
{% extends "core_app/signup_signin_base.html" %}
{%load bootstrap3 %}
{% block title%} Регистрация {% endblock title%}
{% block header %} <h1>Регистрация в сервисе:</h1> {% endblock header %}
{% block content%}
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form user_form%}
    <button type="submit" class="btn btn-submit-red">Зарегистрироваться</button>
  </form>
  <a href="{% url 'core_app:sign-in' %}">Или войти в существующий аккаунт</a>
{% endblock content %}

food_delivery/apps/core_app/templates/core_app/signup_signin_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'core_app/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core_app/css/custom_styles.css' %}">

</head>
<body class="auth-bg">
  <div class="container-fluid">
    <div class="row centered-form">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-body">
          <div class="panel-body">
            <h3 class="text-center text-uppercase">
              <b>{% block header %}{% endblock header %}</b>
            </h3>
            <br/>
              {% block content %}{% endblock content%}
          </div>
          </div>
        </div>
      </div>
    </div>
  <script src="{% static 'core_app/js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'core_app/js/bootstrap.min.js' %}"></script>
</body>  
</html>